package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("abc1234", "credentialsJSON:f1061b5c-1a60-4514-815e-4405ac24f063", display = ParameterDisplay.HIDDEN)
        }
        update {
            text("abc1234", "secret123", allowEmpty = true)
        }
    }
}
